requirements check change

diff --git a/lib/iptv/iptv_main b/lib/iptv/iptv_main
--- a/lib/iptv/iptv_main
+++ b/lib/iptv/iptv_main
@@ -2,6 +2,11 @@
 
 iptv_main() {
 
+    type fzf &>/dev/null
+    if [[ $? != 0 ]]; then
+        error "fzf required"
+    fi
+
     selected=$(cat "$channels_file" | sed 's/ [^ ]*$//' | fzf)
 
     if [ ! -n "$selected" ]; then
diff --git a/lib/kodi/requirements b/lib/kodi/requirements
--- a/lib/kodi/requirements
+++ b/lib/kodi/requirements
@@ -4,11 +4,17 @@ shopt -s nocasematch
 
 type yt-dlp &>/dev/null
 if [[ $? != 0 ]]; then
-    error "yt-dlp install required"
+    error "yt-dlp required"
 fi
-type fzf &>/dev/null
+type jq &>/dev/null
 if [[ $? != 0 ]]; then
-    error "fzf install required"
+    error "jq required"
 fi
+
+## moved to iptv_main
+# type fzf &>/dev/null
+# if [[ $? != 0 ]]; then
+#     error "fzf required"
+# fi
 
 
