Updates to dlrz integration

diff --git a/lib/kodi/kodi_main b/lib/kodi/kodi_main
--- a/lib/kodi/kodi_main
+++ b/lib/kodi/kodi_main
@@ -9,7 +9,10 @@ function kodi_main() {
     if [ -z $INPUT ]; then
 
         read -r -e -d $'\n' -p 'SENDTOKODI[url/path/cmd]: ' INPUT
-
+        if [[ -z $INPUT ]]; then
+            unset INPUT
+            kodi_main
+        fi
         if [[ "$INPUT" =~ ^(exit|quit)$ ]]; then
             unset INPUT
             exit
@@ -73,19 +76,20 @@ function kodi_main() {
             unset INPUT
             ytdl_dlrz
         fi
-        if [[ "$INPUT" =~ ^(mode)$ ]] || [[ "$INPUT" =~ ^(mode)(.[a-z]*)$ ]]; then
-            input_array=($INPUT)
-            unset INPUT
-            #update MODE entry in config file
-            if [[ ${input_array[1]} =~ ^(url|download|stream)$ ]]; then
-                if ! sed -i "s/\(MODE *= *\).*/\1${input_array[1]} \#values\: url\/download\/stream" "$SEND_TO_KODI_CONF"; then
-                    echo "error updating config entry"
-                fi
-                MODE=${input_array[1]}
-            fi
-            echo "Current mode: $MODE"
-            kodi_main
-        fi
+        ## TODO: use this snippit for config update via interface
+        # if [[ "$INPUT" =~ ^(mode)$ ]] || [[ "$INPUT" =~ ^(mode)(.[a-z]*)$ ]]; then
+        #     input_array=($INPUT)
+        #     unset INPUT
+        #     #update MODE entry in config file
+        #     if [[ ${input_array[1]} =~ ^(url|download|stream)$ ]]; then
+        #         if ! sed -i "s/\(MODE *= *\).*/\1${input_array[1]} \#values\: url\/download\/stream" "$SEND_TO_KODI_CONF"; then
+        #             echo "error updating config entry"
+        #         fi
+        #         MODE=${input_array[1]}
+        #     fi
+        #     echo "Current mode: $MODE"
+        #     kodi_main
+        # fi
         if [[ -f "$SEND_TO_KODI_CUSTOM_COMMANDS" ]]; then
             source "$SEND_TO_KODI_CUSTOM_COMMANDS"
         fi
