fixed custom download vs default bug

diff --git a/lib/dlrz/ytdl-dlrz b/lib/dlrz/ytdl-dlrz
--- a/lib/dlrz/ytdl-dlrz
+++ b/lib/dlrz/ytdl-dlrz
@@ -5,17 +5,23 @@ function dlrz_main() {
 
     # dlrz_check_url "$1"
     local url_pattern='(https?|ftp|file|rtsp)://[-[:alnum:]\+&@#/%?=~_|!:,.;]+'
-
+    err=""
+    res=""
     if [[ ! $1 =~ $url_pattern ]]; then
         echo "Unsupported[url/cmd]: $1"
         unset INPUT
         dlrz_read
     fi
     # if ! err=$(yt-dlp -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best --progress --user-agent "'$USER_AGENT'" "$1"); then
-    # if ! err=$(yt-dlp -S res,ext:mp4:m4a --recode mp4 --trim-filenames 50 --user-agent "'$USER_AGENT'" "$1"); then
     # if ! err=$(yt-dlp -S res,ext:mp4:m4a --recode mp4 --limit-rate 500K --user-agent "'$USER_AGENT'" "$1"); then
-    err=""
-    res=""
+    # if err="$($YTDLP -f "bestvideo[height<=$res][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --limit-rate "$LIMIT_RATE" --quiet --progress --user-agent "'$USER_AGENT'" "$1" >&2)"; then
+    function dlrz_dl_default(){
+        echo "Downloading best available" >&2
+        if ! $YTDLP -S vcodec:h264,res,ext:mp4:m4a --recode mp4 --limit-rate "$LIMIT_RATE" --quiet --progress --user-agent "'$USER_AGENT'" "$1" >&2; then
+            echo "Search failed:"
+            dlrz_read
+        fi        
+    }
     if jq -e . >/dev/null 2>&1 <<<"$RESOLUTION_JSON"; then
         while read -r json_string; do
             # Remove escape characters
@@ -26,28 +32,25 @@ function dlrz_main() {
 
                 if [[ "$INPUT" =~ $url_item ]]; then
                     echo "Downloading resolution $res or best available" >&2
-                    # if err="$($YTDLP -f "bestvideo[height<=$res][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --limit-rate "$LIMIT_RATE" --quiet --progress --user-agent "'$USER_AGENT'" "$1" >&2)"; then
-                    if err="$($YTDLP -S vcodec:h264,res:$res,ext:mp4:m4a --recode mp4 --limit-rate "$LIMIT_RATE" --quiet --progress --user-agent "'$USER_AGENT'" "$1" >&2)"; then
-                        # echo "break 1"
+                    if $YTDLP -S vcodec:h264,res:"$res",ext:mp4:m4a --recode mp4 --limit-rate "$LIMIT_RATE" --quiet --progress --user-agent "'$USER_AGENT'" "$1" >&2; then
+                        err=1
                         break
                     fi
                 fi
 
             done <<<"$(echo "$clean_json_string" | jq -r '.value[]')"
 
-            if [[ -z $err ]]; then
-                # echo "break 2"
+            if [[ -n $err ]]; then
                 break
             fi
 
         done <<<"$(echo "$RESOLUTION_JSON" | jq -c '.[]')"
-    else
-        echo "Downloading best available" >&2
-        # if ! err="$($YTDLP -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best --limit-rate "$LIMIT_RATE" --quiet --progress --user-agent "'$USER_AGENT'" "$1" >&2)"; then
-        if err="$($YTDLP -S res,ext:mp4:m4a --recode mp4 --limit-rate "$LIMIT_RATE" --quiet --progress --user-agent "'$USER_AGENT'" "$1" >&2)"; then
-            echo "Search failed: $err"
-            dlrz_read
+
+        if [[ -z $err ]]; then
+            dlrz_dl_default "$@"
         fi
+    else
+        dlrz_dl_default "$@"     
     fi
 
     for i in *.mp4; do
