Remove config option RHEIGHT. Will reuse JSON config for resolution limits

diff --git a/lib/dlrz/ytdl-dlrz b/lib/dlrz/ytdl-dlrz
--- a/lib/dlrz/ytdl-dlrz
+++ b/lib/dlrz/ytdl-dlrz
@@ -16,25 +16,67 @@ function dlrz_main() {
     # if ! err=$(yt-dlp -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best --progress --user-agent "'$USER_AGENT'" "$1"); then
     # if ! err=$(yt-dlp -S res,ext:mp4:m4a --recode mp4 --trim-filenames 50 --user-agent "'$USER_AGENT'" "$1"); then
     # if ! err=$(yt-dlp -S res,ext:mp4:m4a --recode mp4 --limit-rate 500K --user-agent "'$USER_AGENT'" "$1"); then
-    if ! err="$($YTDLP -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best --limit-rate "$LIMIT_RATE" --quiet --progress --user-agent "'$USER_AGENT'" "$1" >&2)"; then
+    # if ! err="$($YTDLP -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best --limit-rate "$LIMIT_RATE" --quiet --progress --user-agent "'$USER_AGENT'" "$1" >&2)"; then
+    #     echo "Search failed: $err"
+    #     dlrz_read
+    # fi
+    err=""
+    res=""
+    if jq -e . >/dev/null 2>&1 <<<"$RESOLUTION_JSON"; then
+        while read -r json_string; do
+            # Remove escape characters
+            clean_json_string=$(echo "$json_string" | jq -r '.')
+            res=$(echo "$clean_json_string" | jq -r '.res')
 
-        echo "Search failed: $err"
-        dlrz_read
+            while read -r url_item; do
+
+                if [[ "$INPUT" =~ $url_item ]]; then
+                    echo "Searching for resolution: $res" >&2
+                    # if ! err="$($YTDLP -f "best[height<=$res]" --limit-rate "$LIMIT_RATE" --quiet --progress --user-agent "'$USER_AGENT'" "$1" >&2)"; then
+                    if err="$($YTDLP -f "bestvideo[height<=$res][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --limit-rate "$LIMIT_RATE" --quiet --progress --user-agent "'$USER_AGENT'" "$1" >&2)"; then
+                        # echo "break 1"
+                        break
+                    fi
+                fi
+
+            done <<<"$(echo "$clean_json_string" | jq -r '.value[]')"
+
+            if [[ -z $err ]]; then
+                # echo "break 2"
+                break
+            fi
+
+        done <<<"$(echo "$RESOLUTION_JSON" | jq -c '.[]')"
     fi
+    # echo "Error: $err"
+    # if [[ -z $err ]] && [[ -n $INPUT ]]; then
+    #     echo "Searching" >&2
+    #     if ! err="$($YTDLP -f bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best --limit-rate "$LIMIT_RATE" --quiet --progress --user-agent "'$USER_AGENT'" "$1" >&2)"; then
+    #         echo "Search failed: $err"
+    #         dlrz_read
+    #     fi
+    # fi
     for i in *.mp4; do
-        if [[ -n $RHEIGHT ]]; then
-            ffmpeg -i "$i" -vf scale=-2:"$RHEIGHT" -preset ultrafast "${i%.*}.$RHEIGHT.mp4"
-            rm "$i"
+
+        curr_res="$(ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 "$i")"
+        echo "$res vs $curr_res" 
+        mtitle="$i"
+        if [[ -n $res ]]; then
+            if [[ ! ${curr_res} =~ $res ]]; then
+                ffmpeg -i "$i" -vf scale=-2:"$res" -preset ultrafast "${i%.*}.$res.mp4"
+                mtitle="${i%.*}.$res.mp4"
+                rm "$i"
+            fi
         fi
         if [[ -n $REMOTE_SSH ]] && [[ -n $REMOTE_PATH ]]; then
 
-            rsync -av --progress --inplace --no-group --no-perms --no-owner "${i%.*}.$RHEIGHT.mp4" "$REMOTE_SSH":"$REMOTE_PATH"
-            rm "${i%.*}.$RHEIGHT.mp4"
+            rsync -av --progress --inplace --no-group --no-perms --no-owner "$mtitle" "$REMOTE_SSH":"$REMOTE_PATH"
+            rm "$mtitle"
 
         elif [[ ! $DOWNLOAD_DIR =~ ^($PWD)$ ]]; then
 
-            rsync -av --progress --inplace --no-group --no-perms --no-owner "${i%.*}.$RHEIGHT.mp4" "$DOWNLOAD_DIR"
-            rm "${i%.*}.$RHEIGHT.mp4"
+            rsync -av --progress --inplace --no-group --no-perms --no-owner "$mtitle" "$DOWNLOAD_DIR"
+            rm "$mtitle"
 
         fi
     done
